"""Inject-and-recover validation (code_review 7.13.1, queue task 1).

One realization per invocation: draw truth (seeded), generate synthetic
data, run the ACTUAL fit through System, and write a json row of
per-parameter pulls (fitted - truth) / sigma_fitted.

v1 SCOPE (recorded deliberately): pulls are asserted for the
LIKELIHOOD-DOMINATED parameters only -- mulens (t_0, u_0, t_E via its
posterior, f_source, f_blend), rv (K, gamma), transit (depth/duration
geometry, in a later leg).  Prior-dominated latents (masses, distances,
proper motions) are excluded from the N(0,1) claim: calibrating those
requires drawing truth from the model's own joint prior
(simulation-based calibration), a different design.  The data are
generated by an INDEPENDENT analytic implementation (Paczynski
magnification, Keplerian RV), not by exozippy's forward model, so a
shared forward-model bug cannot cancel.

Usage: python inject_recover.py --pipeline mulens_pspl --seed 7 \
           --snr 100 --n-epochs 400 --out rows/row_7.json
"""

import argparse
import json
import os
import shutil
import tempfile
from pathlib import Path

import numpy as np
import yaml

HERE = Path(__file__).resolve().parent


def pspl_mag(t, t0, u0, te):
    u = np.sqrt(u0**2 + ((t - t0) / te) ** 2)
    return (u**2 + 2.0) / (u * np.sqrt(u**2 + 4.0))


def make_mulens(rng, snr, n_epochs, workdir):
    """Synthetic PSPL event in a magnitude file + config dict + truth."""
    t0 = 2456000.0 + rng.uniform(-5, 5)
    u0 = rng.uniform(0.05, 0.8) * rng.choice([-1.0, 1.0])
    te = rng.uniform(8.0, 60.0)
    fs = rng.uniform(0.3, 3.0)
    fb = rng.uniform(0.0, 2.0) * fs

    t = np.sort(rng.uniform(t0 - 4 * te, t0 + 4 * te, n_epochs))
    flux = fs * pspl_mag(t, t0, abs(u0), te) + fb
    # snr = peak-flux / sigma_flux
    sig = float(flux.max()) / snr
    flux_obs = flux + rng.normal(0, sig, n_epochs)
    mag = -2.5 * np.log10(np.maximum(flux_obs, 1e-9)) + 22.0
    magerr = 2.5 / np.log(10.0) * sig / np.maximum(flux_obs, 1e-9)
    np.savetxt(workdir / "synth.dat", np.column_stack([t, mag, magerr]))

    config = {
        "star": [{"name": "Lens"}, {"name": "Source"}],
        "lens": [
            {
                "name": "Lens",
                "finite_source": False,
                "lens_ndx": 0,
                "source_ndx": 1,
                "t0_par": float(round(t0, 1)),
                "use_op": False,
                "mmexofast": False,
            }
        ],
        "galacticmodel": [{"name": "synth", "anchor_idx": 1}],
        "band": [{"name": "Cousins_I", "filter": "Cousins_I"}],
        "mulensinstrument": [
            {
                "name": "SYNTH",
                "file": "synth.dat",
                "band": "Cousins_I",
            }
        ],
    }
    # Start near-but-not-at truth (a crude prefit stand-in: 10% scatter),
    # the same information a PSPL prefit supplies in production.
    params = {
        "star.Lens.ra": {"initval": 266.87, "sigma": 0},
        "star.Lens.dec": {"initval": -34.73, "sigma": 0},
        "star.Source.ra": {"initval": 266.87, "sigma": 0},
        "star.Source.dec": {"initval": -34.73, "sigma": 0},
        "lens.Lens.t_0": {"initval": float(t0 + rng.normal(0, 0.1))},
        "lens.Lens.u_0": {"initval": float(u0 * (1 + rng.normal(0, 0.1)))},
        "lens.Lens.t_E": {"initval": float(te * (1 + rng.normal(0, 0.1)))},
    }
    truth = {
        "lens.t_0": t0,
        "lens.u_0": u0,
        "lens.t_E": te,
        "mulensinstrument.f_source": fs / 10 ** (-0.4 * 22.0) * 1e-9,
    }
    # f_source in the file's flux system: F = 10**(-0.4 m); truth fs is in
    # the generator's own units where m = -2.5 log10(F) + 22 -> the file
    # flux system carries F_file = F_gen * 10**(-0.4*22).
    truth["mulensinstrument.f_source"] = fs * 10 ** (-0.4 * 22.0)
    truth["mulensinstrument.f_blend"] = fb * 10 ** (-0.4 * 22.0)
    sampler = {
        "method": "nuts",
        "tune": 1000,
        "draws": 1000,
        "chains": 4,
        "cores": 4,
        "init": "adapt_diag",
        "target_accept": 0.95,
    }
    checks = [
        "lens.t_0",
        "lens.u_0",
        "lens.t_E",
        "mulensinstrument.f_source",
        "mulensinstrument.f_blend",
    ]
    return config, params, sampler, truth, checks


def make_rv(rng, snr, n_epochs, workdir):
    """Synthetic circular-orbit RV series (independent Keplerian)."""
    P = rng.uniform(3.0, 30.0)
    K = rng.uniform(20.0, 200.0)
    tc = 2456000.0 + rng.uniform(0, P)
    gamma = rng.uniform(-30e3, 30e3)
    t = np.sort(2456000.0 + rng.uniform(0, 6 * P, n_epochs))
    rv = gamma + K * np.sin(2 * np.pi * (t - tc) / P + np.pi / 2)
    sig = K / snr
    rv_obs = rv + rng.normal(0, sig, n_epochs)
    np.savetxt(
        workdir / "synth.rv",
        np.column_stack([t, rv_obs, np.full_like(t, sig)]),
    )

    config = {
        "star": [{"name": "Host"}],
        "planet": [
            {"name": "b", "star_ndx": 0, "mass_parameterization": "linear"}
        ],
        "orbit": [
            {"name": "b", "planet_ndx": 0, "star_ndx": 0, "circular": True}
        ],
        "rvinstrument": [{"name": "SYNTH", "file": "synth.rv"}],
    }
    params = {
        "star.Host.mass": {"initval": 1.0, "sigma": 0},
        "star.Host.radius": {"initval": 1.0, "sigma": 0},
        "star.Host.teff": {"initval": 5800.0, "sigma": 0},
        "star.Host.feh": {"initval": 0.0, "sigma": 0},
        "orbit.b.period": {"initval": float(P * (1 + rng.normal(0, 0.001)))},
        "orbit.b.tc": {"initval": float(tc + rng.normal(0, 0.01 * P))},
        "orbit.b.K": {"initval": float(K * (1 + rng.normal(0, 0.1)))},
    }
    truth = {"orbit.K": K, "orbit.period": P, "rvinstrument.gamma": gamma}
    sampler = {
        # period mixes slowly (ESS ~30 at 1000 draws in the shakedown);
        # give the RV leg more room.
        "method": "nuts",
        "tune": 2000,
        "draws": 2000,
        "chains": 4,
        "cores": 4,
        "init": "adapt_diag",
        "target_accept": 0.95,
    }
    checks = ["orbit.K", "orbit.period", "rvinstrument.gamma"]
    return config, params, sampler, truth, checks


# ---------------------------------------------------------------------------
# Transit leg.
#
# The generator is a UNIFORM-DISK (no limb darkening) transit: the exact
# circle-circle overlap area, Mandel & Agol (2002) eq. 1, written out here in
# ~15 lines.  That keeps the harness's independence rule -- the data must not
# come from exozippy's own forward model, or a shared bug cancels -- which a
# limb-darkened generator could not honour without either reimplementing
# Mandel & Agol's I* integrals or borrowing exozippy's.  The fit is therefore
# run with the limb darkening PINNED TO ZERO (ld_law linear, u1 = 0), which
# makes a linear law exactly a uniform disk.  Consequence, recorded so nobody
# reads more into a clean result than is there: this leg validates the TRANSIT
# GEOMETRY (P, tc, Rp/Rstar, b, T14), which is what 7.13.1 asks of it, and
# says nothing about the limb-darkening machinery.
#
# The geometry is drawn CONSISTENTLY rather than independently: a/Rstar is not
# a free draw, it follows from P, Mstar and Rstar through Kepler's third law,
# and cos i follows from b and a/Rstar.  Drawing ar and P independently would
# inject a truth the model cannot represent, and the "pull" would then measure
# our own inconsistency.
# ---------------------------------------------------------------------------
def _overlap_area(z, p):
    """Area of overlap of a unit disk and a disk of radius p at separation z."""
    z = np.asarray(z, dtype=float)
    out = np.zeros_like(z)
    full = z <= (1.0 - p)
    out[full] = np.pi * p * p
    part = (~full) & (z < 1.0 + p)
    zp = z[part]
    k0 = np.arccos(
        np.clip((p * p + zp * zp - 1.0) / (2.0 * p * zp), -1.0, 1.0)
    )
    k1 = np.arccos(np.clip((1.0 - p * p + zp * zp) / (2.0 * zp), -1.0, 1.0))
    rad = np.maximum(4.0 * zp * zp - (1.0 + zp * zp - p * p) ** 2, 0.0)
    out[part] = p * p * k0 + k1 - 0.5 * np.sqrt(rad)
    return out


def make_transit(rng, snr, n_epochs, workdir):
    """Synthetic uniform-disk transit (independent Mandel & Agol geometry)."""
    # G in solar units: Rsun^3 / (Msun day^2).
    G_SUN = 2942.2062
    mstar = float(rng.uniform(0.8, 1.2))
    rstar = float(rng.uniform(0.8, 1.2))
    period = float(rng.uniform(2.0, 10.0))
    a = (G_SUN * mstar * period**2 / (4.0 * np.pi**2)) ** (1.0 / 3.0)
    ar = a / rstar
    p_ratio = float(rng.uniform(0.06, 0.14))
    # b is drawn away from ZERO on purpose.  cos i is bounded below at 0
    # here (see the params block), so a truth at b = 0 would sit exactly ON
    # that bound, where the logit transform diverges and the posterior piles
    # up -- which would corrupt the b and T14 pulls for reasons that have
    # nothing to do with the pipeline.  Central and grazing transits are a
    # separate regime and are deliberately out of scope for this leg.
    b_imp = float(rng.uniform(0.15, 0.60))
    cosi = b_imp / ar
    sini = np.sqrt(max(1.0 - cosi * cosi, 1e-12))
    tc = 2456000.0 + float(rng.uniform(0.0, period))

    # Total (1st-to-4th contact) duration for a circular orbit.
    arg = np.sqrt(max((1.0 + p_ratio) ** 2 - b_imp**2, 0.0)) / (ar * sini)
    t14 = (period / np.pi) * np.arcsin(min(arg, 1.0))

    # Three transits, each covered +/- 1.5 T14 -- ground-based follow-up
    # cadence, and far more constraining per epoch than uniform phase
    # coverage (which would put ~3% of the points in transit).
    n_tr = 3
    per_tr = max(n_epochs // n_tr, 10)
    times = []
    for k in range(n_tr):
        centre = tc + k * period
        times.append(
            rng.uniform(centre - 1.5 * t14, centre + 1.5 * t14, per_tr)
        )
    t = np.sort(np.concatenate(times))

    phase = 2.0 * np.pi * (t - tc) / period
    z = ar * np.sqrt(np.sin(phase) ** 2 + (cosi * np.cos(phase)) ** 2)
    # Only the transit half of the orbit occults; the other half is secondary.
    z = np.where(np.cos(phase) >= 0.0, z, ar)
    flux = 1.0 - _overlap_area(z, p_ratio) / np.pi

    # snr is per-point depth SNR: sigma = depth / snr.
    sig = p_ratio**2 / snr
    flux_obs = flux + rng.normal(0.0, sig, len(t))
    np.savetxt(
        workdir / "synth.trn",
        np.column_stack([t, flux_obs, np.full_like(t, sig)]),
    )

    config = {
        "star": [{"name": "A", "mist": False}],
        "planet": [{"name": "b"}],
        "orbit": [
            {
                "name": "b",
                "primary": ["A"],
                "companion": ["b"],
                # Circular on purpose: the eccentricity coordinates are a
                # separate validation target (Eastman 2024), not this leg's.
                # There is NO `circular:` key -- a circular fit is a
                # sigma:0 + initval:0 pin on BOTH secosw and sesinw (the way
                # examples/kelt17 writes one; Orbit.circular_orbits is the
                # one place that judgement is made).  The transit-only
                # topology also defaults fitvcve/fitchord ON, and
                # circular_orbits is deliberately conservative under
                # fitvcve -- V_c/V_e's inversion is singular at e = 0 -- so
                # fitvcve is turned off explicitly here.  Measured: with
                # "circular": True alone (a key that does not exist) the
                # build left orbit.vcve/xomega/yomega/chord all free.
                #
                # fitchord STAYS ON, and that is deliberate.  The two flags
                # are separable (an explicit fitchord: true is honoured
                # whatever fitvcve is; fitvcve only sets fitchord's
                # DEFAULT), and turning fitchord off is actively harmful
                # here: it hands the fit the conventional cos i coordinate
                # on its [-1, 1] support, and a circular transit with no
                # secondary eclipse and no RV is EXACTLY invariant under
                # cos i -> -cos i, so the posterior goes exactly bimodal.
                # Measured with fitchord off: planet.b at ESS 7.8 / Rhat
                # 1.45 beside orbit.period at ESS 2649 / Rhat 1.012.
                # fitchord does not sample that sign at all -- it takes it
                # from the orbit's i180: convention through the chord_sign
                # context node (orbit.md:104) -- so leaving it on both
                # kills the degeneracy and keeps this leg on the coordinate
                # production actually uses for a transit-only fit.
                "fitvcve": False,
                "fitchord": True,
            }
        ],
        "band": [{"name": "TESS", "filter": "TESS", "ld_law": "linear"}],
        "transit": [{"name": "SYNTH", "file": "synth.trn", "band": "TESS"}],
    }
    params = {
        # The star is not a free parameter of this test: with no SED and no
        # evolutionary model nothing constrains it, and a/Rstar depends on
        # it, so pinning it at truth is what isolates the geometry.
        # NOTE star.mass is DERIVED (10**logmass), so a sigma on it is
        # dropped with a warning and the mass keeps floating -- the pin has
        # to go on the sampled coordinate, star.logmass.  teff/feh are not
        # parameters of this parameterization at all (no SED, no MIST), so
        # pinning them only earns two "sigma is DROPPED" warnings; left out.
        "star.A.logmass": {"initval": float(np.log10(mstar)), "sigma": 0},
        "star.A.radius": {"initval": rstar, "sigma": 0},
        # e = 0 exactly: this is what makes the orbit circular (see above).
        "orbit.b.secosw": {"initval": 0.0, "sigma": 0},
        "orbit.b.sesinw": {"initval": 0.0, "sigma": 0},
        # No bound on cos i is needed or wanted: under fitchord (left on
        # above) cos i is DERIVED and its sign comes from the i180:
        # convention, so there is no bimodality to fence off and a `lower`
        # on a derived parameter would only be a soft barrier layered on
        # the real support.
        # u1 = 0 makes the linear law a uniform disk, matching the generator.
        "band.TESS.u1": {"initval": 0.0, "sigma": 0},
        "orbit.b.period": {
            "initval": float(period * (1 + rng.normal(0, 0.0005)))
        },
        "orbit.b.tc": {"initval": float(tc + rng.normal(0, 0.002 * t14))},
        "planet.b.p": {"initval": float(p_ratio * (1 + rng.normal(0, 0.05)))},
        "planet.b.b": {
            "initval": float(np.clip(b_imp + rng.normal(0, 0.05), 0.0, 0.9))
        },
    }
    truth = {
        "orbit.period": period,
        "orbit.tc": tc,
        "planet.p": p_ratio,
        "planet.b": b_imp,
        "planet.t14": t14,
    }
    sampler = {
        "method": "nuts",
        # 2000/2000: the RV leg's lesson (7.13.1) is that a leg whose rows
        # are convergence-flagged is a leg with no result -- 21 of its 30
        # orbit.period checks failed Rhat/ESS at 2000/2000 and had to be
        # dropped.  Pay for the draws up front here.
        "tune": 2000,
        "draws": 2000,
        "chains": 4,
        "cores": 4,
        "init": "adapt_diag",
        "target_accept": 0.95,
    }
    checks = ["orbit.period", "orbit.tc", "planet.p", "planet.b", "planet.t14"]
    return config, params, sampler, truth, checks


MAKERS = {
    "mulens_pspl": make_mulens,
    "rv": make_rv,
    "transit": make_transit,
}


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--pipeline", required=True, choices=sorted(MAKERS))
    ap.add_argument("--seed", type=int, required=True)
    ap.add_argument("--snr", type=float, default=100.0)
    ap.add_argument("--n-epochs", type=int, default=400)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    out_path = Path(args.out).resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(args.seed)
    workdir = Path(tempfile.mkdtemp(prefix=f"ir_{args.pipeline}_"))
    os.chdir(workdir)

    config, params, sampler, truth, checks = MAKERS[args.pipeline](
        rng, args.snr, args.n_epochs, workdir
    )

    import pymc as pm

    from exozippy.system import System

    system = System(dict(config), user_params=dict(params))
    system.prepare()
    model = system.build_model()
    with model:
        idata = pm.sample(
            draws=sampler["draws"],
            tune=sampler["tune"],
            chains=sampler["chains"],
            cores=sampler["cores"],
            target_accept=sampler["target_accept"],
            progressbar=False,
            random_seed=args.seed,
        )

    post = idata.posterior
    row = {
        "pipeline": args.pipeline,
        "seed": args.seed,
        "snr": args.snr,
        "n_epochs": args.n_epochs,
    }
    import arviz as az
    import pytensor

    def draws_of(name):
        """Draws of element 0 of a check quantity: from the trace for
        sampled parameters, evaluated through the model graph for DERIVED
        ones (t_E, f_source... are Parameters, not posterior variables)."""
        if name in post:
            da = post[name]
            v = np.asarray(da).reshape(-1, *da.shape[2:])
            v = v[:, 0] if v.ndim > 1 else v
            return v, da
        comp_name, pname = name.split(".", 1)
        param = getattr(getattr(system, comp_name), pname)
        (node,) = model.replace_rvs_by_values([param.value])
        fn = pytensor.function(
            model.value_vars, node, on_unused_input="ignore"
        )
        names_v = [vv.name for vv in model.value_vars]
        raws = [
            np.asarray(post[n]).reshape(-1, *np.asarray(post[n]).shape[2:])
            for n in names_v
        ]
        n_draws = raws[0].shape[0]
        step = max(1, n_draws // 2000)  # <= ~2000 evals per quantity
        out = np.array(
            [
                np.atleast_1d(fn(*[r[k] for r in raws]))[0]
                for k in range(0, n_draws, step)
            ]
        )
        return out, None

    for name in checks:
        tval = truth[name]
        v, da = draws_of(name)
        # INTERNAL -> USER units: posterior Deterministics and Parameter
        # value graphs are internal (orbit.K and gamma in solRad/d); the
        # injected truths are user units (m/s).  The first RV shakedown
        # "failed" with pull ~ -1.7e6 purely from this -- K was recovered
        # to 1% once converted.  Parameter.from_internal is the one
        # sanctioned direction (CLAUDE.md's reciprocal-factors rule).
        comp_name, pname = name.split(".", 1)
        param = getattr(getattr(system, comp_name), pname)
        v = np.asarray([float(param.from_internal(x, index=0)) for x in v])
        v_raw = v
        # signed parameters: fold the reflection PER DRAW (u_0 -> -u_0 is
        # a mode; folding the median of a sign-mixing posterior would
        # average the modes instead)
        if name == "lens.u_0":
            v, tval = np.abs(v), abs(tval)
        med = float(np.median(v))
        lo, hi = np.percentile(v, [15.865, 84.135])
        sig = 0.5 * (hi - lo)
        # The PULL assumes a symmetric posterior: it compares a point
        # estimate to truth in units of half the 68% interval.  Where the
        # marginal is SKEWED that statistic is biased even when the
        # posterior is perfectly calibrated -- measured on this very
        # harness for lens.t_E, whose pull mean runs -1.24 +/- 0.40 at
        # snr=30, -0.58 at 100 and +0.26 at 300, with a pull distribution
        # whose negative tail reaches -4.8 while its positive tail stops
        # at +1.1.
        #
        # So also record the QUANTILE of truth within the posterior draws
        # (the probability integral transform).  Under correct calibration
        # this is UNIFORM(0,1) whatever the posterior's shape, which makes
        # it the right calibration statistic for a skewed marginal and the
        # standard one for simulation-based calibration.  Keep both: the
        # pull is what a reader of the paper table experiences, the
        # quantile is what tests the posterior.
        q = float(np.mean(v < tval))
        row[name] = {
            "truth": float(tval),
            "median": med,
            "sigma": float(sig),
            "pull": float((med - tval) / sig) if sig > 0 else None,
            "quantile": q,
            "n_draws": int(v.size),
        }
        if da is not None:
            row[name]["ess"] = float(az.ess(da).values.min())
            row[name]["rhat"] = float(az.rhat(da).values.max())
        else:
            # DERIVED check: there is no posterior variable to hand arviz, so
            # this branch used to record no diagnostic at all -- and the one
            # check that turned out to have a problem (lens.t_E) was derived,
            # so it silently escaped every convergence filter.  Rebuild a
            # (chain, draw) view of the evaluated quantity and diagnose it
            # like any other.  draws_of() strides the flattened draws, so the
            # chain structure has to be restored by reshaping on the stride.
            n_ch = int(post.sizes["chain"])
            if n_ch > 1 and v_raw.size >= 2 * n_ch:
                per = v_raw.size // n_ch
                arr = v_raw[: n_ch * per].reshape(n_ch, per)
                try:
                    da2 = az.convert_to_dataset({name: arr[None, ...][0]})
                    row[name]["ess"] = float(az.ess(da2).to_array().min())
                    row[name]["rhat"] = float(az.rhat(da2).to_array().max())
                    row[name]["diag_source"] = "derived-reshaped"
                except Exception as exc:  # noqa: BLE001
                    row[name]["diag_note"] = "no diagnostic: %r" % (exc,)
    with open(out_path, "w") as f:
        json.dump(row, f, indent=1)
    print(
        json.dumps(
            {
                k: (v["pull"] if isinstance(v, dict) else v)
                for k, v in row.items()
            },
            indent=1,
        )
    )
    shutil.rmtree(workdir, ignore_errors=True)


if __name__ == "__main__":
    main()
