"""
Shared observer-ephemeris utilities.

Computes barycentric (ICRS/J2000 equatorial) observer positions in AU for
any component that needs them (microlensing parallax, astrometry parallax
factors, ...).  Supports major solar-system bodies, topocentric ground
sites, and interpolated spacecraft ephemeris files (see ephemerides/ and
ephemerides/get_ephemeris.py to generate new ones from JPL Horizons).
"""

import logging
import os
import warnings

import numpy as np
from scipy.interpolate import CubicSpline

from astropy.coordinates import (
    get_body_barycentric,
    solar_system_ephemeris,
    EarthLocation,
    ICRS,
)
from astropy.time import Time

logger = logging.getLogger(__name__)

# Package-internal directory of spacecraft ephemeris files (*.eph)
EPHEMERIDES_DIR = os.path.join(os.path.dirname(__file__), 'ephemerides')


def get_observer_position(time, observer_location='earth'):
    """
    High-precision observer position dispatcher.

    Parameters:
    -----------
    time : float or ndarray
        Time(s) at which to calculate coordinates (BJD_TDB).
    observer_location : str
        One of:
          - Major bodies ('earth', 'moon')
          - Topocentric ground sites ('lat,lon,alt' or a site name like 'CTIO')
          - Spacecraft ephemeris files ('gaia', 'spitzer', or a path to a
            file generated by ephemerides/get_ephemeris.py)

    Returns:
    --------
    xyz_au : ndarray
        (N, 3) array of barycentric X, Y, Z coordinates in AU (ICRS/J2000
        equatorial frame).
    """
    solar_system_ephemeris.set('jpl')
    t_obj = Time(time, format='jd', scale='tdb')

    # 1. Handle Terrestrial / Topocentric (Lat/Lon)
    # Check if string looks like "lat, lon, alt" or a known site name
    try:
        if ',' in observer_location:
            # Parse "lat, lon, alt"
            loc = EarthLocation.from_geodetic(*[float(x) for x in observer_location.split(',')])
        else:
            # Check for site names like 'CTIO' or 'Siding Spring'
            loc = EarthLocation.of_site(observer_location)

        # Get topocentric position: Barycentric Earth + Geocentric Offset
        # This accounts for Earth's orbit and the observer's specific spot on the globe
        return loc.get_itrs(t_obj).transform_to(ICRS()).cartesian.xyz.to('au').value.T
    except Exception:
        # Not a ground site, move to next check
        pass

    # 2. Handle Major Bodies
    if observer_location in ['earth', 'moon']:
        return get_body_barycentric(observer_location, t_obj).xyz.to('au').value.T

    # 3. Handle Satellite Ephemeris Files with Search Paths
    search_paths = [
        observer_location,  # absolute/relative path
        os.path.join(EPHEMERIDES_DIR, observer_location),  # Package internal
        os.path.join(EPHEMERIDES_DIR, observer_location + '.eph')  # Package internal
    ]

    for path in search_paths:
        if os.path.exists(path):
            return interpolate_ephemeris(time, path)

    raise ValueError(
        f"observer location not recognized: {observer_location}; see "
        f"$EXOZIPPY_PATH/src/exozippy/ephemerides/get_ephemeris.py to generate an ephemeris")


def interpolate_ephemeris(time, ephemeris_file):
    """
    Interpolates a Barycentric ephemeris file.

    Parameters:
    -----------
    time : float or ndarray
        The time(s) at which to calculate coordinates (BJD_TDB).
    ephemeris_file : str
        Path to the file generated by ephemerides/get_ephemeris.py
        (Format: BJD_TDB, X, Y, Z)

    Returns:
    --------
    xyz_au : ndarray
        (N, 3) array of X, Y, Z coordinates in AU.
    """
    # Load data, skipping the header lines
    # data[:, 0] = BJD_TDB, [:, 1:4] = X, Y, Z
    data = np.loadtxt(ephemeris_file)

    t_grid = data[:, 0]
    xyz_grid = data[:, 1:4]

    # Check if we are extrapolating (which is dangerous)
    t_min, t_max = np.min(t_grid), np.max(t_grid)
    if np.any(time < t_min) or np.any(time > t_max):
        warnings.warn(f"Extrapolating outside ephemeris range! "
                      f"Grid: {t_min:.2f}-{t_max:.2f}, Requested: {np.min(time):.2f}")

    # Create the spline object
    # bc_type='not-a-knot' is standard for smooth orbital curves
    cs = CubicSpline(t_grid, xyz_grid, axis=0, bc_type='not-a-knot')

    return cs(time)
