"""Every shipped example config must still reach a prepared System.

This is a rot guard, not a science test. The examples are the documentation
of the YAML surface, and nothing else in the suite touches most of them -- so
an API migration can silently leave one behind. That is exactly what happened
to examples/hat3: its `band:` block had an entry with no `name:` and its
transits still used the pre-Band `filter:` key, so `System.prepare()` died
with "Transit instrument(s) reference unknown band(s)" and nothing noticed.
examples/hd80606 had the same disease one rename earlier (`inst.` for
`rvinstrument.` in its params file).

Scope is deliberately `prepare()` only (stages 1-3: file I/O, index maps,
parameter registration, the relaxation engine). That is where a stale key,
a dangling cross-reference or a renamed prefix shows up, and it costs a
couple of seconds per example. Building the PyMC model, let alone sampling,
would cost minutes each and is covered per-feature elsewhere
(tests/test_integration_kelt4.py and friends).

Examples that genuinely cannot run here belong in ``_EXCLUDED`` with a
reason, never dropped silently.
"""

import os
from pathlib import Path

import pytest
import yaml

from exozippy.system import System

_EXAMPLES = Path(__file__).parent.parent / "examples"

# Relative path (POSIX, from examples/) -> reason it cannot be prepared here.
# Empty today: every shipped config prepares. Add entries rather than
# narrowing the glob, so an excluded example stays visible.
_EXCLUDED: dict[str, str] = {}


def _system_configs():
    """Every examples/*/ YAML that is a system config, as (path, id) pairs.

    A system config is identified by content, not filename: it carries a
    `run:` or `sampler:` block. Parameter files, `.sed` files and the SED
    photometry YAMLs carry neither, and the naming is not consistent enough
    to key on (examples/hat3 spells its SED file `hat3_sed.yaml`, everyone
    else `<name>.sed.yaml`).
    """
    out = []
    if not _EXAMPLES.is_dir():
        return out
    for path in sorted(_EXAMPLES.glob("*/*.yaml")):
        try:
            doc = yaml.safe_load(path.read_text())
        except yaml.YAMLError:
            # A config that will not even parse is a failure, not a
            # non-config: keep it so the test reports it.
            doc = {"sampler": None}
        if not isinstance(doc, dict):
            continue
        if "run" not in doc and "sampler" not in doc:
            continue
        out.append((path, path.relative_to(_EXAMPLES).as_posix()))
    return out


_CONFIGS = _system_configs()


@pytest.mark.parametrize(
    "path,rel", _CONFIGS, ids=[rel for _, rel in _CONFIGS]
)
def test_shipped_example_prepares(path, rel, monkeypatch, caplog):
    """Given a shipped example config and its parameter file, when
    System.prepare() runs from the example's own directory, then it
    completes, every active component has a registered manifest, and no
    top-level YAML key was ignored as unrecognized."""
    # Arrange
    if rel in _EXCLUDED:
        pytest.skip(f"{rel}: {_EXCLUDED[rel]}")

    config = yaml.safe_load(path.read_text())
    monkeypatch.chdir(path.parent)

    param_file = config.get("parameter_file")
    user_params = None
    if param_file is not None:
        pf = Path(param_file)
        assert pf.is_file(), (
            f"{rel} names parameter_file '{param_file}', which does not "
            f"exist relative to {os.getcwd()}"
        )
        user_params = yaml.safe_load(pf.read_text())

    # Act
    with caplog.at_level("WARNING", logger="exozippy"):
        system = System(config, user_params)
        system.prepare()

    # Assert
    assert system.active_components, f"{rel} instantiated no components"
    for key, comp in system.active_components.items():
        assert hasattr(comp, "manifest"), (
            f"{rel}: component '{key}' registered no manifest in stage 2"
        )

    ignored = [
        r.getMessage()
        for r in caplog.records
        if "does not match any registered component" in r.getMessage()
    ]
    assert not ignored, f"{rel} has stale top-level YAML key(s): {ignored}"


def test_every_example_directory_has_a_config():
    """Given the examples/ tree, when its directories are enumerated, then
    each one either ships a system config this test collects or is listed
    as a data/workflow-only directory -- so a new example cannot be added
    in a way that this guard silently skips."""
    # Arrange: directories that hold data or a driver workflow, not a
    # config exozippy can be pointed at directly.
    data_only = {
        # Driver scripts only: one config per Roman Data Challenge event is
        # generated by the job pipeline, not committed (see the DC2018
        # section of CLAUDE.md).
        "DC2018",
        # README only -- no data and no config committed yet.
        "KMT-2021-BLG-1122L",
        "ob161045",
    }
    covered = {rel.split("/")[0] for _, rel in _CONFIGS}

    # Act: dot/underscore directories are caches and local scratch, not
    # examples.
    dirs = {
        p.name
        for p in _EXAMPLES.iterdir()
        if p.is_dir() and not p.name.startswith((".", "_"))
    }

    # Assert
    uncovered = dirs - covered - data_only
    assert not uncovered, (
        f"examples/ directories with no collected system config: "
        f"{sorted(uncovered)}. Add a config, or list the directory in "
        f"this test's data_only set with a reason."
    )
