# /bin/sh
#$ -S /bin/sh
#$ -pe mthread 16
#$ -q sThC.q
#$ -cwd
#$ -j y
#$ -N dc18alpha
#$ -o dc18_alpha_convention.$JOB_ID.log

module purge
module load tools/python/3.13
export PATH="$HOME/miniconda3/bin:$PATH:$HOME/.local/bin"
source $HOME/miniconda3/etc/profile.d/conda.sh
conda activate exozippy

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1

cd $HOME/python/EXOZIPPy/examples/DC2018
python -u dc18_alpha_convention.py
