"""The ``<prefix>_paper.tex`` writer: a compilable paper-draft scaffold.

Renders ``system.prose`` (see ``outputs/prose.py``) into ONE minimal but
compilable aastex document, and copies the shipped support files
(``aastex701.cls``, ``aasjournalv7.bst``, ``references.bib`` -- see
``src/exozippy/latex/README.md``) next to it, so the output directory is a
self-contained LaTeX project: ``pdflatex && bibtex && pdflatex &&
pdflatex`` works on a machine with a bare TeX Live and no AASTeX.

The file is REGENERATED from the in-memory collector at each checkpoint --
right after ``build_model()`` (the citation scaffold exists before
sampling starts, and survives a fit that dies hours in) and again at
wrap-up, when the post-fit sections, figures and table exist.  It is never
appended to on disk: literal appending double-appends on reload paths and
cannot update a sentence.  Anything not yet on disk simply is not
included: the parameter-table fragment and each figure are ``\\input`` /
``\\includegraphics``'d only if the file exists at write time, so the same
call serves both checkpoints.

This module owns the ONE standalone LaTeX wrapper.  ``outputs/latex.py``
writes fragments (the ``\\providecommand`` definitions and the
deluxetable body); historically the table file was itself a standalone
document, whose preamble is now here.

The preamble is ``aastex701`` and nothing else.  A ``\\usepackage
{apjfonts}`` line used to follow in the table template, and it made the
generated file uncompilable anywhere that file was missing: apjfonts is a
legacy AASTeX v5 font package, it is NOT on CTAN and NOT in TeX Live, and
its absence is fatal ("LaTeX Error: File `apjfonts.sty' not found.
Emergency stop."), not degraded.  AASTeX 7 sets its own fonts -- AAS's own
aastex701-sample.tex does not load apjfonts.  Do not add it back.
"""

import logging
import os
import shutil
import subprocess
from pathlib import Path

from .prose import POST_FIT_SECTIONS, SECTION_ORDER
from .texutils import latex_escape

logger = logging.getLogger(__name__)

# Shipped LaTeX support files (src/exozippy/latex/, package data).
SUPPORT_DIR = Path(__file__).parent.parent / "latex"
SUPPORT_FILES = ("aastex701.cls", "aasjournalv7.bst", "references.bib")

# Always in the \software{...} line; components add the optional stack
# (celerite2, MulensModel, ...) via system.prose.add_software at the site
# that uses it.
CORE_SOFTWARE = ("EXOZIPPy", "numpy", "PyMC", "PyTensor", "ArviZ")

# Document sections: (\section title, prose sections rendered into it, in
# collector order).  A document section with no sentences is omitted.
_DOC_SECTIONS = (
    ("Observations", ("data",)),
    (
        "Modeling",
        (
            "intro",
            "stellar",
            "planetary",
            "orbits",
            "microlensing",
            "noise",
            "priors",
            "sampling",
        ),
    ),
    ("Results", POST_FIT_SECTIONS),
)
# Every prose section must be routed into exactly one document section, or
# a sentence lands in no paragraph -- checked at import so a vocabulary
# edit cannot silently drop prose.
_ROUTED = tuple(s for _, secs in _DOC_SECTIONS for s in secs)
assert sorted(_ROUTED) == sorted(SECTION_ORDER), (
    "prose sections not routed into the document: "
    f"{set(SECTION_ORDER) ^ set(_ROUTED)}"
)

_HEADER = """\
% {basename} -- auto-generated by EXOZIPPy.
%
% A CRUDE STARTING POINT for a paper's modeling section, built so that
% every citation relevant to how this fit was configured is already in
% place.  The prose is deliberately mechanical -- rewrite it; the
% citations are the part meant to survive.
%
% THIS FILE IS OVERWRITTEN each time the fit (or exozippy-modes) runs.
% Rename it or copy it into your manuscript before editing.
%
% Self-contained: aastex701.cls, aasjournalv7.bst and references.bib are
% copied alongside, so this compiles with a bare TeX Live:
%   pdflatex {stem} && bibtex {stem} && pdflatex {stem} && pdflatex {stem}
% references.bib is EXOZIPPy's full reference library; bibtex picks out
% the cited entries, and the rest may be handy as you write.
"""


def _figure_block(pdf_name, caption, tag):
    return (
        "\\begin{figure}[htb!]\n"
        "\\centering\n"
        f"\\includegraphics[width=\\linewidth]{{{pdf_name}}}\n"
        f"\\caption{{{caption}\\label{{fig:{tag}}}}}\n"
        "\\end{figure}\n"
    )


def collect_figures(system, prefix, point=None):
    """``[(pdf basename, caption LaTeX, tag), ...]`` for the draft's figures.

    Walks every component's ``plot_data(system, point)`` specs and pairs
    each spec's posterior PDF -- ``{prefix}_mcmc_{file_tag}.pdf``, the name
    ``plotrender`` writes for the final plots -- with its
    ``meta['caption']``.  Only PDFs that exist on disk are returned, which
    is what makes the same writer serve the pre-sample checkpoint (no
    plots yet -> no figures section) and wrap-up.  A spec without a
    caption gets a generic one built from its title, marked for the user
    to replace.

    ``point`` matters at wrap-up: several components return their
    model-bearing specs (phased RV/LC panels) only when given a parameter
    point, so run.py hands one posterior draw through -- without it those
    figures exist on disk but are absent from the draft.  Falls back to
    the data-only specs per component if a point evaluation fails.
    """
    figures = []
    seen = set()
    for comp in system.active_components.values():
        specs = None
        if point is not None:
            try:
                specs = comp.plot_data(system, point) or []
            except Exception:
                logger.debug(
                    "plot_data(point) failed for %s; falling back to "
                    "data-only specs for its figure list",
                    getattr(comp, "prefix", comp.__class__.__name__),
                    exc_info=True,
                )
        if specs is None:
            try:
                specs = comp.plot_data(system) or []
            except Exception:
                logger.warning(
                    "plot_data failed for %s while collecting figures "
                    "(non-fatal; its figures are omitted from modeling.tex)",
                    getattr(comp, "prefix", comp.__class__.__name__),
                    exc_info=True,
                )
                continue
        for spec in specs:
            tag = spec.meta.get("file_tag") or spec.id.replace(".", "_")
            if tag in seen:
                continue
            seen.add(tag)
            pdf = f"{prefix}_mcmc_{tag}.pdf"
            if not os.path.exists(pdf):
                continue
            caption = spec.meta.get("caption")
            if not caption:
                caption = (
                    latex_escape(spec.title)
                    + ". (Auto-generated caption -- describe this figure.)"
                )
            figures.append((os.path.basename(pdf), caption, tag))
    return figures


def render_document(
    system,
    basename,
    var_stem=None,
    table_stem=None,
    figures=(),
):
    """The full modeling.tex text, from ``system.prose``.

    ``var_stem`` / ``table_stem`` are the ``\\input`` stems of the
    definitions and deluxetable fragments (None omits them -- the
    pre-sample checkpoint).  ``figures`` is ``collect_figures`` output.
    """
    prose = system.prose
    stem = basename[: -len(".tex")] if basename.endswith(".tex") else basename
    lines = [_HEADER.format(basename=basename, stem=stem)]
    lines.append(r"\documentclass[twocolumn]{aastex701}")
    if var_stem:
        # The \providecommand set: every \ez... macro the table (and any
        # prose that cites a fitted value) resolves against.
        lines.append(rf"\input{{{var_stem}}}")
    lines.append(r"\begin{document}")
    # System.name defaults to the literal "system" when the config sets no
    # top-level name: -- the output prefix is the better identity then.
    name = getattr(system, "name", None)
    if not name or name == "system":
        name = stem[: -len("_paper")] if stem.endswith("_paper") else stem
    lines.append(rf"\title{{Draft: modeling of {latex_escape(name)}}}")
    lines.append("")

    for heading, sections in _DOC_SECTIONS:
        paragraphs = prose.paragraphs(sections=sections)
        if not paragraphs:
            continue
        lines.append(rf"\section{{{heading}}}")
        lines.append("")
        for _, texts in paragraphs:
            lines.append(" ".join(texts))
            lines.append("")

    if table_stem:
        lines.append(rf"\input{{{table_stem}}}")
        lines.append("")
    for pdf_name, caption, tag in figures:
        lines.append(_figure_block(pdf_name, caption, tag))

    software = list(CORE_SOFTWARE) + [
        s for s in prose.software if s not in CORE_SOFTWARE
    ]
    lines.append(rf"\software{{{', '.join(software)}}}")
    lines.append("")
    lines.append(r"\bibliographystyle{aasjournalv7}")
    lines.append(r"\bibliography{references}")
    lines.append(r"\end{document}")
    return "\n".join(lines) + "\n"


def copy_support_files(out_dir):
    """Copy the shipped .cls/.bst/.bib next to the generated .tex.

    Copies (never symlinks -- the point is a directory that can be
    tarballed onto another machine) and overwrites: the shipped versions
    supersede whatever an older EXOZIPPy left there.  Failure to copy is a
    warning, not an error; the .tex still compiles anywhere the files are
    installed.
    """
    for name in SUPPORT_FILES:
        src = SUPPORT_DIR / name
        try:
            shutil.copy(src, Path(out_dir) / name)
        except OSError:
            logger.warning(
                "Could not copy %s next to modeling.tex; the document "
                "will only compile where AASTeX/the references are "
                "already installed",
                src,
                exc_info=True,
            )


def build_modeling_output(system, prefix, point=None):
    """(Re)generate ``<prefix>_paper.tex`` and its support files.

    Called at both checkpoints (post-``build_model()`` and wrap-up); what
    differs between them is only what exists -- post-fit prose sections in
    the collector, the table fragments and figure PDFs on disk.  ``point``
    (one posterior draw, wrap-up only) unlocks the model-bearing plot
    specs so the phased panels' figures make it in.  Returns the path to
    the .tex.
    """
    prefix = str(prefix)
    tex_path = prefix + "_paper.tex"
    base = os.path.basename(prefix)

    # The fragments report_pipeline writes at wrap-up; \input'd by bare
    # stem, so modeling.tex must live in the same directory (it does: same
    # prefix).
    var_stem = base + "_definitions"
    table_stem = base + "_table"
    if not os.path.exists(prefix + "_definitions.tex"):
        var_stem = None
    if not os.path.exists(prefix + "_table.tex"):
        table_stem = None

    text = render_document(
        system,
        os.path.basename(tex_path),
        var_stem=var_stem,
        table_stem=table_stem,
        figures=collect_figures(system, prefix, point=point),
    )
    with open(tex_path, "w") as f:
        f.write(text)
    copy_support_files(os.path.dirname(tex_path) or ".")
    logger.info("Wrote %s", tex_path)
    return tex_path


def compile_modeling_pdf(tex_path, timeout=600):
    """Compile modeling.tex to PDF: pdflatex, bibtex, pdflatex, pdflatex.

    Returns the PDF path, or None when TeX is unavailable or the compile
    fails.  NEVER raises: the PDF is a bonus deliverable and no wrap-up
    step may kill a finished multi-day fit -- the .tex sources remain the
    deliverable either way, and a failure warns with the .log path.

    bibtex exit status 1 means warnings only (e.g. nothing cited yet at
    the pre-sample checkpoint); only >= 2 is an error, and even that is
    non-fatal here since pdflatex still produces a PDF without a .bbl.
    """
    tex_path = Path(tex_path)
    if shutil.which("pdflatex") is None:
        logger.info(
            "pdflatex not found; skipping the modeling-draft PDF "
            "(%s and its support files compile on any machine with TeX)",
            tex_path.name,
        )
        return None

    cwd = tex_path.parent if str(tex_path.parent) else Path(".")
    stem = tex_path.stem
    steps = [["pdflatex", "-interaction=nonstopmode", stem + ".tex"]]
    if shutil.which("bibtex") is not None:
        steps.append(["bibtex", stem])
    else:
        logger.warning(
            "bibtex not found; the modeling draft compiles without its "
            "bibliography"
        )
    steps += [
        ["pdflatex", "-interaction=nonstopmode", stem + ".tex"],
        ["pdflatex", "-interaction=nonstopmode", stem + ".tex"],
    ]

    # Best-effort: a failing pass does NOT abort the rest of the cycle.
    # In nonstopmode pdflatex still writes a complete PDF past most errors,
    # and the later passes are what resolve \cite and \ref -- aborting on
    # pass 1 is how the DC2018_128 draft shipped with every citation as
    # (?) and 'Table ??' over one undefined macro.  Failures are collected
    # and reported once, naming the log.
    log_path = cwd / (stem + ".log")
    failures = []
    for cmd in steps:
        try:
            result = subprocess.run(
                cmd,
                cwd=cwd,
                capture_output=True,
                text=True,
                timeout=timeout,
            )
        except (OSError, subprocess.TimeoutExpired) as exc:
            logger.warning(
                "%s failed while building the modeling draft (%s); "
                "see %s -- the .tex sources are unaffected",
                cmd[0],
                exc,
                log_path,
            )
            return None
        failed = (
            result.returncode >= 2
            if cmd[0] == "bibtex"
            else result.returncode != 0
        )
        if failed:
            failures.append(f"{cmd[0]} exited {result.returncode}")

    pdf_path = cwd / (stem + ".pdf")
    if not pdf_path.exists():
        logger.warning(
            "the modeling draft did not produce %s (%s); see %s -- the "
            ".tex sources are unaffected",
            pdf_path,
            "; ".join(failures) or "no step reported failure",
            log_path,
        )
        return None
    if failures:
        logger.warning(
            "Compiled %s, but with LaTeX errors (%s); inspect %s "
            "(and %s for the bibliography)",
            pdf_path,
            "; ".join(failures),
            log_path,
            cwd / (stem + ".blg"),
        )
    else:
        logger.info("Compiled %s", pdf_path)
    return pdf_path
