"""Shared LaTeX plumbing for the report layer.

One escaping helper, used everywhere a string that is NOT meant to be LaTeX
reaches a LaTeX file: the output prefix, target/system names, instrument and
band (instance) names, component section labels, parameter descriptions.

Underscores are the common case and they are not exotic -- ``DC2018_128``,
``KMT-2019-BLG-1806_nt8long``, ``MEARTH_20090513`` are all real prefixes and
instrument names in this repo -- and a raw one in text mode is a hard
``Missing $ inserted`` at the very end of a long fit.

Deliberately NOT escaped (these are meant to carry math/markup):

- ``Parameter.latex`` -- the symbol column, e.g. ``\\log{g_*}``;
- ``Parameter.unit_latex`` -- generated by UnitTranslator;
- ``Parameter.table_note`` -- e.g. ``Derived from \\citet{Chen:2017}``;
- ``build_latex_output(caption=..., tablecomments=...)`` -- pass-through
  prose the caller composes; escape the untrusted *pieces* before
  concatenating (see report_pipeline's caption).
"""

# Order matters: the backslash rule must run first, and its replacement
# must not be re-processed by the later rules (hence the two-step dance
# through a placeholder that contains no special character).
_BACKSLASH_PLACEHOLDER = "\x00ezbackslash\x00"

_REPLACEMENTS = (
    ("&", r"\&"),
    ("%", r"\%"),
    ("$", r"\$"),
    ("#", r"\#"),
    ("_", r"\_"),
    ("{", r"\{"),
    ("}", r"\}"),
    ("~", r"\textasciitilde{}"),
    ("^", r"\textasciicircum{}"),
)


def latex_escape(text):
    """Return ``text`` with every LaTeX special character escaped.

    ``None`` maps to ``""``; anything else is stringified first, so callers
    can pass numpy scalars and Path objects straight through.
    """
    if text is None:
        return ""
    out = str(text).replace("\\", _BACKSLASH_PLACEHOLDER)
    for old, new in _REPLACEMENTS:
        out = out.replace(old, new)
    return out.replace(_BACKSLASH_PLACEHOLDER, r"\textbackslash{}")
